name: kuyijia_flutter_demo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: ^4.0.2
  image_picker: ^0.4.10
  fluttertoast: ^2.1.5
  flutter_sound: ^1.2.1
#  audio_recorder2: ^1.0.3
  intl: ^0.15.7
#  scoped_model: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo/kuyijialogo.jpg
    - images/nav/order.png
    - images/nav/order_selected.png
    - images/nav/add.png
    - images/nav/add_selected.png
    - images/nav/mine.png
    - images/nav/mine_selected.png
    - images/icon/arrow_right.png
    - images/icon/icon_bg.png
    - images/icon/WechatIMG5.jpeg
    - images/icon/NewOrder.png
    - images/icon/pp.png
    - images/icon/choose_camera.png
    - images/icon/choose_gallery.png
    - images/icon/delete.png
    - images/icon/voice.png

    - images/ic_play.png
    - images/2.0x/ic_play.png
    - images/3.0x/ic_play.png
    - images/ic_stop.png
    - images/2.0x/ic_stop.png
    - images/3.0x/ic_stop.png
    - images/ic_pause.png
    - images/2.0x/ic_pause.png
    - images/3.0x/ic_pause.png
    - images/ic_mic.png
    - images/2.0x/ic_mic.png
    - images/3.0x/ic_mic.png
    - images/ic_volume_down.png
    - images/2.0x/ic_volume_down.png
    - images/3.0x/ic_volume_down.png
    - images/ic_volume_up.png
    - images/2.0x/ic_volume_up.png
    - images/3.0x/ic_volume_up.png
    - images/gif/huatong.gif


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
